stages:
- test

install:
        stage: test
        image: python:latest
        script:
        - python3 setup.py install
        only:
        - master

download:
        stage: test
        script:
        - python3 setup.py install
        - youtube-sm --init subscription_manager
        - youtube-sm
        - wc -l sub.html
        - youtube-sm --debug -m json --output test.json
        - wc -l test.json
        - youtube-sm --html -l [youtube] UC-lHJZR3Gqxm24_Vd_AJ5Yw -m list -t -1 --output test.list -r --debug
        - wc -l test.list
        - youtube-sm --ultra-html -l [youtube] UCEcNXmr7DYq1XxpWHSxaN0w -m raw -t -1 -r --output test.raw --debug
        - wc -l test.raw
        - youtube-sm -l [peertube] thinkerview.video:5 -m raw -t -1 -r --output test.raw --debug
        - wc -l test.raw
        - youtube-sm -l [peertube] thinkerview.video -m raw -t -1 -r --output test.raw --debug
        - wc -l test.raw
        - youtube-sm -l [test] test -m raw -t -1 -r --output test.raw --debug
        - curl -O https://sawyerf.gitlab.io/youtube_sm/test.swy
        - youtube-sm --debug --init test.swy
        - youtube-sm --debug -t -1 --output testall.html
        - wc -l testall.html
        - youtube-sm --debug

commands:
        stage: test
        script:
        - python3 setup.py install
        - youtube-sm 
        - youtube-sm -h
        - youtube-sm --css ""
        - youtube-sm --css
        - youtube-sm -a [youtube] UC-lHJZR3Gqxm24_Vd_AJ5Yw --debug
        - youtube-sm -a [peertube] thinkerview.video:5 --debug
        - youtube-sm -a [dailymotion] karimdebbache --debug

